# Generated by Django 4.2.28 on 2026-02-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0002_cab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pooled', 'Pooled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pooled', max_length=20)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='rides.cab')),
            ],
            options={
                'verbose_name': 'Pool',
                'verbose_name_plural': 'Pools',
                'ordering': ['-created_at'],
            },
        ),
    ]
