# Generated by Django 4.2.28 on 2026-02-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_cab'),
        ('pooling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_order', models.PositiveSmallIntegerField(default=1)),
                ('pickup_eta', models.DateTimeField(blank=True, null=True)),
                ('drop_eta', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pooling.pool')),
                ('ride_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='rides.riderequest')),
            ],
            options={
                'verbose_name': 'Pool Member',
                'verbose_name_plural': 'Pool Members',
                'ordering': ['sequence_order'],
                'unique_together': {('pool', 'ride_request')},
            },
        ),
    ]
