# Generated by Django 4.2.28 on 2026-02-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_lat', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('drop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('seats_required', models.PositiveSmallIntegerField(default=1)),
                ('luggage_units', models.PositiveSmallIntegerField(default=1)),
                ('detour_tolerance_minutes', models.PositiveSmallIntegerField(default=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pooled', 'Pooled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to='users.user')),
            ],
            options={
                'verbose_name': 'Ride Request',
                'verbose_name_plural': 'Ride Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
