# Generated by Django 4.2.28 on 2026-02-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('total_seats', models.PositiveSmallIntegerField(default=4)),
                ('luggage_capacity', models.PositiveSmallIntegerField(default=4)),
                ('current_lat', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], db_index=True, default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Cab',
                'verbose_name_plural': 'Cabs',
            },
        ),
    ]
